import { NextRequest } from 'next/server';
import { auditLimiter } from '@/lib/rateLimit';
import { anthropicProvider } from '@/lib/ai/anthropicProvider';
import { STREAM_RESPONSE_HEADERS } from '@/lib/config/apiHeaders';
import { escapeXml } from '@/lib/escapeXml';
import { chatRequestSchema } from '@/lib/schemas/chatRequest';

export const runtime = 'nodejs';

const CHAT_SYSTEM_PROMPT = `You are a senior code auditor answering follow-up questions about an audit you just performed.

You have access to the original code that was audited and the audit results. Answer questions concisely and precisely:
- Reference specific findings by their IDs when applicable
- Provide code examples for fixes when asked
- Explain the reasoning behind severity ratings
- Suggest concrete next steps

Understanding the audit's finding tags:
- [CERTAIN] = definitively confirmed issue. [LIKELY] = strong evidence but depends on runtime context. [POSSIBLE] = speculative, may be a false positive.
- [VULNERABILITY] = exploitable issue. [DEFICIENCY] = best-practice gap with real impact. [SUGGESTION] = nice-to-have improvement, not a defect.
- If a user asks whether a finding is real, consider its confidence tag. [POSSIBLE] findings are worth investigating but may not apply.
- If a user says a finding is wrong, acknowledge it — false positives can occur, especially for [LIKELY] and [POSSIBLE] findings.

Keep answers focused and under 400 words unless the user asks for detailed code.`;

const STREAM_TIMEOUT_MS = 60_000;

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

export async function POST(req: NextRequest) {
  const ip =
    req.headers.get('x-forwarded-for')?.split(',')[0].trim() ??
    req.headers.get('x-real-ip') ??
    '127.0.0.1';

  const rl = await auditLimiter.check(ip);
  if (!rl.allowed) {
    return new Response('Too many requests.', { status: 429, headers: rl.headers });
  }

  let rawBody: unknown;
  try {
    rawBody = await req.json();
  } catch {
    return new Response('Invalid JSON', { status: 400 });
  }

  // ARCH-REVIEW-005: Zod schema validation — consistent with /api/audit pattern.
  const parsed = chatRequestSchema.safeParse(rawBody);
  if (!parsed.success) {
    const message = parsed.error.issues[0]?.message ?? 'Invalid request';
    return new Response(message, { status: 400 });
  }

  const { messages, context } = parsed.data;

  // Build system prompt with audit context
  const systemPrompt = context
    ? `${CHAT_SYSTEM_PROMPT}\n\n<audit_context>\n${escapeXml(context)}\n</audit_context>`
    : CHAT_SYSTEM_PROMPT;

  // PROMPT-INJ-002: XML-escape and delimit user messages to match the structural
  // defence applied to audit input in /api/audit. Assistant messages are trusted
  // (generated by the model) so they pass through unmodified.
  const chatMessages: ChatMessage[] = messages.map((m) => ({
    role: m.role,
    content: m.role === 'user'
      ? `<user_message>\n${escapeXml(m.content)}\n</user_message>`
      : m.content,
  }));

  const stream = anthropicProvider.streamChat(
    systemPrompt,
    chatMessages,
    { signal: AbortSignal.timeout(STREAM_TIMEOUT_MS) },
  );

  return new Response(stream, {
    headers: STREAM_RESPONSE_HEADERS,
  });
}
